name: main

on: 
   push:
   schedule:
      - cron: '*/10 * * * *'

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
         pip install requests
         pip install BeautifulSoup4
      - name: pull changes
        run: git pull
      - name: execute script
        run: python scrape-counters.py
      - name: commit changes
        run: |
            git config --global user.name 'Colin G. Wilson'
            git config --global user.email 'colingwilson7@gmail.com'
            git add --all
            git commit -am "Automated"
            git push
